### PR TITLE
 Add Ukrainian translations

### PR DESCRIPTION
**Pull request by olexandr-konovalov**
@dpshelio I've added Ukrainian translations as you explained!

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
@dpshelio ping?

**Review by dpshelio — APPROVED** [review]

**Comment by olexandr-konovalov** [comment]
@dpshelio thanks!

**Comment by olexandr-konovalov** [comment]
P.S. @dpshelio https://carpentries-i18n.github.io/python-novice-gapminder/ is not automatically updated, right?

**Comment by dpshelio** [comment]
No, it's not automatic. It only pulls from the theme each time it is built. I've created an issue carpentries-i18n/i18n#31

**Pull request merged**
