### PR TITLE
Add assets for Japanese

### PR DESCRIPTION
**Pull request by TomKellyGenetics**
Adds file for Japanese language: https://github.com/swcarpentry-ja/carp-theme/blob/master/assets/i18n/ja.md

### CODE REVIEW

**Comment by TomKellyGenetics** [comment]
Not sure this merges properly but the asset file works for Japanese and has been checked by native speakers.

**Comment by TomKellyGenetics** [comment]
Conflicts resolved! (mostly I think)

**Comment by TomKellyGenetics** [comment]
File `jp.md` (softlink) removed to avoid confusion: https://www.localeplanet.com/icu/ja-JP/index.html

**Comment by TomKellyGenetics** [comment]
I've tested building webpages on our fork with updated assets. Once this PR is merged, I will revert these changes to link to the branch here to keep updated.

```diff
-remote_theme: "carpentries-i18n/carp-theme"
+remote_theme: "swcarpentry-ja/carp-theme"
```

https://github.com/swcarpentry-ja/r-novice-gapminder/commit/1aaf65f36ed0ddcea9ba5f1cc3eadeff31bf3dd5
https://github.com/swcarpentry-ja/git-novice/commit/243cca58ccd2bcb6682cc7325da4ef7dd905d4bb

**Comment by TomKellyGenetics** [comment]
> Conflicts resolved! (mostly I think)

Actually resolved now :)

**Comment by dpshelio** [comment]
Closed in favor of #9

**Pull request closed without merging**
